### ISSUE TITLE
Make sample data file available

### ISSUE THREAD

**Issue by joewiz** [ljo/exist-tei-graphing#1]
Would it be possible to make a sample data file, such as the one referenced in the README.md file, available? Or a link to it where people could download the file? This way people could test out the app on data that is known to conform to the app's requirements.

**Comment by joewiz** [comment]
I googled and think I found it: http://www.dramawebben.se/sites/default/files/dw-delkorpus1/IndebetouH_IDetGrona.xml.

Adapting this to the sample code in README.md, my first attempt returned an error:

```xquery
xquery version "3.0";
import module namespace graphing="http://exist-db.org/xquery/tei-graphing";
declare namespace tei="http://www.tei-c.org/ns/1.0";
let $doc := doc("http://www.dramawebben.se/sites/default/files/dw-delkorpus1/IndebetouH_IDetGrona.xml")
return
graphing:relation-graph($doc//tei:listPerson[not(parent::tei:listPerson)], $doc//tei:listRelation, <parameters><param name="output" value="graphml"/></parameters>)
```

The error:

```text
2017-02-13 12:37:05,425 [qtp122060903-41] ERROR (XQueryServlet.java [process]:534) - null 
java.lang.NullPointerException: null
	at org.exist.xquery.tei.graphing.Visualization.parseListPersonGroup(Visualization.java:527) ~[exist-tei-graphing-0.2.jar:?]
	at org.exist.xquery.tei.graphing.Visualization.parseListPersons(Visualization.java:224) ~[exist-tei-graphing-0.2.jar:?]
	at org.exist.xquery.tei.graphing.Visualization.parseNamesDates(Visualization.java:189) ~[exist-tei-graphing-0.2.jar:?]
	at org.exist.xquery.tei.graphing.Visualization.eval(Visualization.java:119) ~[exist-tei-graphing-0.2.jar:?]
	at org.exist.xquery.BasicFunction.eval(BasicFunction.java:73) ~[exist.jar:?]
	at org.exist.xquery.InternalFunctionCall.eval(InternalFunctionCall.java:41) ~[exist.jar:?]
	at org.exist.xquery.DebuggableExpression.eval(DebuggableExpression.java:58) ~[exist.jar:?]
	at org.exist.xquery.LetExpr.eval(LetExpr.java:111) ~[exist.jar:?]
	at org.exist.xquery.AbstractExpression.eval(AbstractExpression.java:71) ~[exist.jar:?]
	at org.exist.xquery.PathExpr.eval(PathExpr.java:276) ~[exist.jar:?]
	at org.exist.xquery.AbstractExpression.eval(AbstractExpression.java:71) ~[exist.jar:?]
	at org.exist.xquery.XQuery.execute(XQuery.java:253) ~[exist.jar:?]
	at org.exist.xquery.XQuery.execute(XQuery.java:185) ~[exist.jar:?]
	at org.exist.http.servlets.XQueryServlet.process(XQueryServlet.java:470) [exist-optional.jar:?]
	at org.exist.http.servlets.XQueryServlet.doPost(XQueryServlet.java:191) [exist-optional.jar:?]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707) [servlet-api-3.1.jar:3.1.0]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790) [servlet-api-3.1.jar:3.1.0]
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:845) [jetty-servlet-9.3.9.v20160517.jar:9.3.9.v20160517]
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:583) [jetty-servlet-9.3.9.v20160517.jar:9.3.9.v20160517]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143) [jetty-server-9.3.9.v20160517.jar:9.3.9.v20160517]
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:566) [jetty-security-9.3.9.v20160517.jar:9.3.9.v20160517]
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226) [jetty-server-9.3.9.v20160517.jar:9.3.9.v20160517]
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1174) [jetty-server-9.3.9.v20160517.jar:9.3.9.v20160517]
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:511) [jetty-servlet-9.3.9.v20160517.jar:9.3.9.v20160517]
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185) [jetty-server-9.3.9.v20160517.jar:9.3.9.v20160517]
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1106) [jetty-server-9.3.9.v20160517.jar:9.3.9.v20160517]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) [jetty-server-9.3.9.v20160517.jar:9.3.9.v20160517]
	at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:159) [jetty-server-9.3.9.v20160517.jar:9.3.9.v20160517]
	at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:74) [jetty-server-9.3.9.v20160517.jar:9.3.9.v20160517]
	at org.exist.http.urlrewrite.Forward.doRewrite(Forward.java:50) [exist-optional.jar:?]
	at org.exist.http.urlrewrite.XQueryURLRewrite.doRewrite(XQueryURLRewrite.java:545) [exist-optional.jar:?]
	at org.exist.http.urlrewrite.XQueryURLRewrite.service(XQueryURLRewrite.java:349) [exist-optional.jar:?]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790) [servlet-api-3.1.jar:3.1.0]
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:845) [jetty-servlet-9.3.9.v20160517.jar:9.3.9.v20160517]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1689) [jetty-servlet-9.3.9.v20160517.jar:9.3.9.v20160517]
	at de.betterform.agent.web.filter.XFormsFilter.doFilter(XFormsFilter.java:171) [betterform-exist-5.1-SNAPSHOT-20160615.jar:?]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1668) [jetty-servlet-9.3.9.v20160517.jar:9.3.9.v20160517]
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:581) [jetty-servlet-9.3.9.v20160517.jar:9.3.9.v20160517]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143) [jetty-server-9.3.9.v20160517.jar:9.3.9.v20160517]
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:524) [jetty-security-9.3.9.v20160517.jar:9.3.9.v20160517]
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226) [jetty-server-9.3.9.v20160517.jar:9.3.9.v20160517]
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1174) [jetty-server-9.3.9.v20160517.jar:9.3.9.v20160517]
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:511) [jetty-servlet-9.3.9.v20160517.jar:9.3.9.v20160517]
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185) [jetty-server-9.3.9.v20160517.jar:9.3.9.v20160517]
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1106) [jetty-server-9.3.9.v20160517.jar:9.3.9.v20160517]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) [jetty-server-9.3.9.v20160517.jar:9.3.9.v20160517]
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:213) [jetty-server-9.3.9.v20160517.jar:9.3.9.v20160517]
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:119) [jetty-server-9.3.9.v20160517.jar:9.3.9.v20160517]
	at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:396) [jetty-server-9.3.9.v20160517.jar:9.3.9.v20160517]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134) [jetty-server-9.3.9.v20160517.jar:9.3.9.v20160517]
	at org.eclipse.jetty.server.Server.handle(Server.java:524) [jetty-server-9.3.9.v20160517.jar:9.3.9.v20160517]
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:319) [jetty-server-9.3.9.v20160517.jar:9.3.9.v20160517]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:253) [jetty-server-9.3.9.v20160517.jar:9.3.9.v20160517]
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273) [jetty-io-9.3.9.v20160517.jar:9.3.9.v20160517]
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95) [jetty-io-9.3.9.v20160517.jar:9.3.9.v20160517]
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93) [jetty-io-9.3.9.v20160517.jar:9.3.9.v20160517]
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303) [jetty-util-9.3.9.v20160517.jar:9.3.9.v20160517]
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148) [jetty-util-9.3.9.v20160517.jar:9.3.9.v20160517]
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136) [jetty-util-9.3.9.v20160517.jar:9.3.9.v20160517]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671) [jetty-util-9.3.9.v20160517.jar:9.3.9.v20160517]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589) [jetty-util-9.3.9.v20160517.jar:9.3.9.v20160517]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
```

Storing this in the database works:

```xquery
xquery version "3.0";
import module namespace graphing="http://exist-db.org/xquery/tei-graphing";
declare namespace tei="http://www.tei-c.org/ns/1.0";
let $remote-doc := doc("http://www.dramawebben.se/sites/default/files/dw-delkorpus1/IndebetouH_IDetGrona.xml")
let $store := xmldb:store('/db', 'IndebetouH_IDetGrona.xml', $remote-doc)
let $doc := doc($store)
return
graphing:relation-graph($doc//tei:listPerson[not(parent::tei:listPerson)], $doc//tei:listRelation, <parameters><param name="output" value="graphml"/></parameters>)
```

Results:

```xml
<gml:graphml xmlns:gml="http://graphml.graphdrawing.org/xmlns">
    <gml:key id="d0" for="node" attr.name="number" attr.type="int"/>
    <gml:key id="d1" for="node" attr.name="subject" attr.type="string"/>
    <gml:key id="d2" for="node" attr.name="type" attr.type="string"/>
    <gml:key id="d3" for="edge" attr.name="number" attr.type="int"/>
    <gml:key id="d4" for="edge" attr.name="relation" attr.type="string"/>
    <gml:key id="d5" for="edge" attr.name="weight" attr.type="int"/>
    <gml:key id="d6" for="edge" attr.name="type" attr.type="string"/>
    <gml:graph id="g0" edgedefault="undirected" parse.nodeids="canonical" parse.edgeids="canonical" parse.order="nodesfirst">
        <gml:node id="n0">
            <gml:data key="d0">0</gml:data>
            <gml:data key="d1">Moje</gml:data>
            <gml:data key="d2">cast person</gml:data>
        </gml:node>
        <gml:node id="n1">
            <gml:data key="d0">1</gml:data>
            <gml:data key="d1">Kandidaten</gml:data>
            <gml:data key="d2">cast person</gml:data>
        </gml:node>
        <gml:node id="n2">
            <gml:data key="d0">2</gml:data>
            <gml:data key="d1">Jungfrun</gml:data>
            <gml:data key="d2">cast person</gml:data>
        </gml:node>
        <gml:node id="n3">
            <gml:data key="d0">3</gml:data>
            <gml:data key="d1">KandidatensFar</gml:data>
            <gml:data key="d2">cast person</gml:data>
        </gml:node>
        <gml:node id="n4">
            <gml:data key="d0">4</gml:data>
            <gml:data key="d1">Agda</gml:data>
            <gml:data key="d2">cast person</gml:data>
        </gml:node>
        <gml:node id="n5">
            <gml:data key="d0">5</gml:data>
            <gml:data key="d1">Lilly</gml:data>
            <gml:data key="d2">cast person</gml:data>
        </gml:node>
        <gml:node id="n6">
            <gml:data key="d0">6</gml:data>
            <gml:data key="d1">Löjtnanten</gml:data>
            <gml:data key="d2">cast person</gml:data>
        </gml:node>
        <gml:node id="n7">
            <gml:data key="d0">7</gml:data>
            <gml:data key="d1">FruMarika</gml:data>
            <gml:data key="d2">cast person</gml:data>
        </gml:node>
        <gml:node id="n8">
            <gml:data key="d0">8</gml:data>
            <gml:data key="d1">FarbrorFritz</gml:data>
            <gml:data key="d2">cast person</gml:data>
        </gml:node>
        <gml:node id="n9">
            <gml:data key="d0">9</gml:data>
            <gml:data key="d1">Patronen</gml:data>
            <gml:data key="d2">cast person</gml:data>
        </gml:node>
        <gml:node id="n10">
            <gml:data key="d0">10</gml:data>
            <gml:data key="d1">Mia</gml:data>
            <gml:data key="d2">cast person</gml:data>
        </gml:node>
        <gml:node id="n11">
            <gml:data key="d0">11</gml:data>
            <gml:data key="d1">Lundqvist</gml:data>
            <gml:data key="d2">cast person</gml:data>
        </gml:node>
        <gml:node id="n12">
            <gml:data key="d0">12</gml:data>
            <gml:data key="d1">Pojken</gml:data>
            <gml:data key="d2">cast person</gml:data>
        </gml:node>
        <gml:node id="n13">
            <gml:data key="d0">13</gml:data>
            <gml:data key="d1">MosterUlla</gml:data>
            <gml:data key="d2">cast person</gml:data>
        </gml:node>
        <gml:node id="n14">
            <gml:data key="d0">14</gml:data>
            <gml:data key="d1">Pojkar</gml:data>
            <gml:data key="d2">cast person</gml:data>
        </gml:node>
        <gml:node id="n15">
            <gml:data key="d0">15</gml:data>
            <gml:data key="d1">Doktorinnan</gml:data>
            <gml:data key="d2">cast person</gml:data>
        </gml:node>
        <gml:edge id="e0" directed="false" source="n3" target="n8">
            <gml:data key="d3">0</gml:data>
            <gml:data key="d4">vän</gml:data>
            <gml:data key="d6">personal</gml:data>
        </gml:edge>
        <gml:edge id="e1" directed="true" source="n11" target="n7">
            <gml:data key="d3">1</gml:data>
            <gml:data key="d4">anställd</gml:data>
            <gml:data key="d6">social</gml:data>
        </gml:edge>
        <gml:edge id="e2" directed="true" source="n4" target="n1">
            <gml:data key="d3">2</gml:data>
            <gml:data key="d4">frierska</gml:data>
            <gml:data key="d6">personal</gml:data>
        </gml:edge>
        <gml:edge id="e3" directed="false" source="n14" target="n0">
            <gml:data key="d3">3</gml:data>
            <gml:data key="d4">kamrat</gml:data>
            <gml:data key="d6">personal</gml:data>
        </gml:edge>
        <gml:edge id="e4" directed="true" source="n4" target="n7">
            <gml:data key="d3">4</gml:data>
            <gml:data key="d4">dotter</gml:data>
            <gml:data key="d6">personal</gml:data>
        </gml:edge>
        <gml:edge id="e5" directed="true" source="n1" target="n3">
            <gml:data key="d3">5</gml:data>
            <gml:data key="d4">son</gml:data>
            <gml:data key="d6">personal</gml:data>
        </gml:edge>
        <gml:edge id="e6" directed="true" source="n13" target="n7">
            <gml:data key="d3">6</gml:data>
            <gml:data key="d4">släkting</gml:data>
            <gml:data key="d6">personal</gml:data>
        </gml:edge>
        <gml:edge id="e7" directed="true" source="n5" target="n15">
            <gml:data key="d3">7</gml:data>
            <gml:data key="d4">dotter</gml:data>
            <gml:data key="d6">personal</gml:data>
        </gml:edge>
        <gml:edge id="e8" directed="true" source="n8" target="n15">
            <gml:data key="d3">8</gml:data>
            <gml:data key="d4">fdfriare</gml:data>
            <gml:data key="d6">personal</gml:data>
        </gml:edge>
        <gml:edge id="e9" directed="true" source="n4" target="n5">
            <gml:data key="d3">9</gml:data>
            <gml:data key="d4">konkurrent</gml:data>
            <gml:data key="d6">personal</gml:data>
        </gml:edge>
        <gml:edge id="e10" directed="true" source="n8" target="n7">
            <gml:data key="d3">10</gml:data>
            <gml:data key="d4">släkting</gml:data>
            <gml:data key="d6">personal</gml:data>
        </gml:edge>
        <gml:edge id="e11" directed="true" source="n4" target="n6">
            <gml:data key="d3">11</gml:data>
            <gml:data key="d4">frierska</gml:data>
            <gml:data key="d6">personal</gml:data>
        </gml:edge>
        <gml:edge id="e12" directed="true" source="n1" target="n9">
            <gml:data key="d3">12</gml:data>
            <gml:data key="d4">släkting</gml:data>
            <gml:data key="d6">personal</gml:data>
        </gml:edge>
        <gml:edge id="e13" directed="true" source="n10" target="n9">
            <gml:data key="d3">13</gml:data>
            <gml:data key="d4">dotter</gml:data>
            <gml:data key="d6">personal</gml:data>
        </gml:edge>
        <gml:edge id="e14" directed="true" source="n10" target="n7">
            <gml:data key="d3">14</gml:data>
            <gml:data key="d4">dotter</gml:data>
            <gml:data key="d6">personal</gml:data>
        </gml:edge>
        <gml:edge id="e15" directed="true" source="n4" target="n9">
            <gml:data key="d3">15</gml:data>
            <gml:data key="d4">dotter</gml:data>
            <gml:data key="d6">personal</gml:data>
        </gml:edge>
        <gml:edge id="e16" directed="true" source="n5" target="n13">
            <gml:data key="d3">16</gml:data>
            <gml:data key="d4">gäst</gml:data>
            <gml:data key="d6">personal</gml:data>
        </gml:edge>
        <gml:edge id="e17" directed="true" source="n2" target="n13">
            <gml:data key="d3">17</gml:data>
            <gml:data key="d4">jungfru</gml:data>
            <gml:data key="d6">social</gml:data>
        </gml:edge>
        <gml:edge id="e18" directed="true" source="n0" target="n9">
            <gml:data key="d3">18</gml:data>
            <gml:data key="d4">son</gml:data>
            <gml:data key="d6">personal</gml:data>
        </gml:edge>
        <gml:edge id="e19" directed="false" source="n5" target="n1">
            <gml:data key="d3">19</gml:data>
            <gml:data key="d4">förlovad</gml:data>
            <gml:data key="d6">personal</gml:data>
        </gml:edge>
        <gml:edge id="e20" directed="true" source="n6" target="n5">
            <gml:data key="d3">20</gml:data>
            <gml:data key="d4">friare</gml:data>
            <gml:data key="d6">personal</gml:data>
        </gml:edge>
        <gml:edge id="e21" directed="true" source="n8" target="n1">
            <gml:data key="d3">21</gml:data>
            <gml:data key="d4">välgörare</gml:data>
            <gml:data key="d6">personal</gml:data>
        </gml:edge>
        <gml:edge id="e22" directed="true" source="n8" target="n9">
            <gml:data key="d3">22</gml:data>
            <gml:data key="d4">släkting</gml:data>
            <gml:data key="d6">personal</gml:data>
        </gml:edge>
        <gml:edge id="e23" directed="true" source="n11" target="n9">
            <gml:data key="d3">23</gml:data>
            <gml:data key="d4">anställd</gml:data>
            <gml:data key="d6">social</gml:data>
        </gml:edge>
        <gml:edge id="e24" directed="false" source="n9" target="n7">
            <gml:data key="d3">24</gml:data>
            <gml:data key="d4">gift</gml:data>
            <gml:data key="d6">personal</gml:data>
        </gml:edge>
        <gml:edge id="e25" directed="true" source="n1" target="n7">
            <gml:data key="d3">25</gml:data>
            <gml:data key="d4">släkting</gml:data>
            <gml:data key="d6">personal</gml:data>
        </gml:edge>
        <gml:edge id="e26" directed="true" source="n13" target="n8">
            <gml:data key="d3">26</gml:data>
            <gml:data key="d4">släkting</gml:data>
            <gml:data key="d6">personal</gml:data>
        </gml:edge>
        <gml:edge id="e27" directed="true" source="n13" target="n15">
            <gml:data key="d3">27</gml:data>
            <gml:data key="d4">släkting</gml:data>
            <gml:data key="d6">personal</gml:data>
        </gml:edge>
        <gml:edge id="e28" directed="true" source="n0" target="n7">
            <gml:data key="d3">28</gml:data>
            <gml:data key="d4">son</gml:data>
            <gml:data key="d6">personal</gml:data>
        </gml:edge>
        <gml:edge id="e29" directed="true" source="n12" target="n15">
            <gml:data key="d3">29</gml:data>
            <gml:data key="d4">ror</gml:data>
            <gml:data key="d6">other</gml:data>
        </gml:edge>
        <gml:edge id="e30" directed="false" source="n14" target="n10">
            <gml:data key="d3">30</gml:data>
            <gml:data key="d4">kamrat</gml:data>
            <gml:data key="d6">personal</gml:data>
        </gml:edge>
    </gml:graph>
</gml:graphml>
```

Is this correct - that the graphic module requires that the documents be stored in the database?

Switching the output to SVG and loading the result in the browser yields this:

> ![screen shot 2017-02-13 at 12 40 49 pm](https://cloud.githubusercontent.com/assets/59118/22895229/b88cdb20-f1e9-11e6-9021-4b05ed771800.png)

This result might be nice to include in the README.md.
